version: "3.8"

services:
  grpc-api:
    image: ghcr.io/deephaven/grpc-api:${VERSION:-latest}
    expose:
      - '8080'
    tmpfs:
      - /cache
      - /tmp
    volumes:
      - data:/data

  web:
    image: ghcr.io/deephaven/web:${VERSION:-latest}
    expose:
      - '80'
    tmpfs:
      - /tmp

  grpc-proxy:
    image: ghcr.io/deephaven/grpc-proxy:${VERSION:-latest}
    environment:
      - BACKEND_ADDR=grpc-api:8080
    depends_on:
      - grpc-api
    expose:
      - '8080'
    tmpfs:
      - /tmp

  envoy:
    image: ghcr.io/deephaven/envoy:${VERSION:-latest}
    depends_on:
      - web
      - grpc-proxy
      - grpc-api
    ports:
      - "${PORT:-10000}:10000"
    tmpfs:
      - /tmp

volumes:
    data: